const cssData = [
  {category:"布局", props:[
    {name:"display", desc:"定义元素的显示类型", values:"none | block | inline | inline-block | flex | inline-flex | grid | inline-grid | table | table-cell | list-item | contents", initial:"inline", inherited:"否", common:true},
    {name:"position", desc:"定义元素的定位方式", values:"static | relative | absolute | fixed | sticky", initial:"static", inherited:"否", common:true},
    {name:"top", desc:"上偏移", values:"auto | <length> | <percentage>", initial:"auto", inherited:"否", common:true},
    {name:"right", desc:"右偏移", values:"auto | <length> | <percentage>", initial:"auto", inherited:"否", common:true},
    {name:"bottom", desc:"下偏移", values:"auto | <length> | <percentage>", initial:"auto", inherited:"否", common:true},
    {name:"left", desc:"左偏移", values:"auto | <length> | <percentage>", initial:"auto", inherited:"否", common:true},
    {name:"z-index", desc:"层级顺序", values:"auto | <integer>", initial:"auto", inherited:"否", common:true},
    {name:"float", desc:"浮动", values:"none | left | right | inline-start | inline-end", initial:"none", inherited:"否", common:true},
    {name:"clear", desc:"清除浮动", values:"none | left | right | both | inline-start | inline-end", initial:"none", inherited:"否", common:true},
    {name:"vertical-align", desc:"垂直对齐", values:"baseline | sub | super | top | text-top | middle | bottom | text-bottom | <length> | <percentage>", initial:"baseline", inherited:"否", common:true},
    {name:"aspect-ratio", desc:"宽高比", values:"auto | <ratio>", initial:"auto", inherited:"否", common:true},
    {name:"flex", desc:"弹性子元素伸缩简写", values:"none | [flex-grow flex-shrink? | flex-basis]", initial:"0 1 auto", inherited:"否", common:true},
    {name:"flex-direction", desc:"主轴方向", values:"row | row-reverse | column | column-reverse", initial:"row", inherited:"否", common:true},
    {name:"flex-wrap", desc:"是否换行", values:"nowrap | wrap | wrap-reverse", initial:"nowrap", inherited:"否", common:true},
    {name:"justify-content", desc:"主轴对齐", values:"flex-start | flex-end | center | space-between | space-around | space-evenly", initial:"flex-start", inherited:"否", common:true},
    {name:"align-items", desc:"交叉轴对齐", values:"stretch | flex-start | flex-end | center | baseline", initial:"stretch", inherited:"否", common:true},
    {name:"align-self", desc:"单个交叉轴对齐", values:"auto | stretch | flex-start | flex-end | center | baseline", initial:"auto", inherited:"否", common:false},
    {name:"align-content", desc:"多行交叉轴对齐", values:"stretch | flex-start | flex-end | center | space-between | space-around", initial:"stretch", inherited:"否", common:false},
    {name:"justify-items", desc:"主轴对齐所有子项", values:"auto | normal | start | end | center | stretch | baseline", initial:"auto", inherited:"否", common:true},
    {name:"justify-self", desc:"单个子项主轴对齐", values:"auto | normal | start | end | center | stretch | baseline", initial:"auto", inherited:"否", common:false},
    {name:"place-content", desc:"内容对齐简写", values:"<align-content> <justify-content>?", initial:"normal auto", inherited:"否", common:false},
    {name:"place-items", desc:"子项对齐简写", values:"<align-items> <justify-items>?", initial:"normal auto", inherited:"否", common:true},
    {name:"place-self", desc:"单个子项对齐简写", values:"<align-self> <justify-self>?", initial:"auto auto", inherited:"否", common:false},
    {name:"flex-grow", desc:"放大比例", values:"<number>", initial:"0", inherited:"否", common:false},
    {name:"flex-shrink", desc:"缩小比例", values:"<number>", initial:"1", inherited:"否", common:false},
    {name:"flex-basis", desc:"初始大小", values:"<length> | <percentage> | auto | content", initial:"auto", inherited:"否", common:false},
    {name:"grid-template-columns", desc:"网格列定义", values:"none | <track-list>", initial:"none", inherited:"否", common:true},
    {name:"grid-template-rows", desc:"网格行定义", values:"none | <track-list>", initial:"none", inherited:"否", common:true},
    {name:"grid-column", desc:"网格列位置简写", values:"<grid-line> / <grid-line>?", initial:"auto", inherited:"否", common:true},
    {name:"grid-column-start", desc:"网格列起始线", values:"auto | <custom-ident> | <integer> | span <integer> | span <custom-ident>", initial:"auto", inherited:"否", common:false},
    {name:"grid-column-end", desc:"网格列结束线", values:"auto | <custom-ident> | <integer> | span <integer> | span <custom-ident>", initial:"auto", inherited:"否", common:false},
    {name:"grid-row", desc:"网格行位置简写", values:"<grid-line> / <grid-line>?", initial:"auto", inherited:"否", common:true},
    {name:"grid-row-start", desc:"网格行起始线", values:"auto | <custom-ident> | <integer> | span <integer> | span <custom-ident>", initial:"auto", inherited:"否", common:false},
    {name:"grid-row-end", desc:"网格行结束线", values:"auto | <custom-ident> | <integer> | span <integer> | span <custom-ident>", initial:"auto", inherited:"否", common:false},
    {name:"grid-area", desc:"网格区域简写", values:"<row-start> / <col-start> / <row-end> / <col-end>", initial:"auto", inherited:"否", common:false},
    {name:"grid-template-areas", desc:"网格区域命名", values:"none | <string>+", initial:"none", inherited:"否", common:false},
    {name:"grid-auto-flow", desc:"自动放置方式", values:"row | column | row dense | column dense", initial:"row", inherited:"否", common:false},
    {name:"grid-auto-rows", desc:"自动行大小", values:"<length> | <percentage> | auto", initial:"auto", inherited:"否", common:false},
    {name:"grid-auto-columns", desc:"自动列大小", values:"<length> | <percentage> | auto", initial:"auto", inherited:"否", common:false},
    {name:"grid-template", desc:"网格模板简写", values:"none | <rows> / <cols>", initial:"none", inherited:"否", common:false},
    {name:"grid", desc:"网格简写", values:"none | <grid-template> | <rows> / <cols>", initial:"none", inherited:"否", common:false},
    {name:"gap", desc:"子元素间距简写", values:"<row-gap> <column-gap>?", initial:"normal", inherited:"否", common:true},
    {name:"row-gap", desc:"行间距", values:"normal | <length> | <percentage>", initial:"normal", inherited:"否", common:true},
    {name:"column-gap", desc:"列间距", values:"normal | <length> | <percentage>", initial:"normal", inherited:"否", common:true},
    {name:"inset", desc:"定位内边距简写", values:"<top> <right> <bottom> <left>?", initial:"auto", inherited:"否", common:true},
    {name:"overflow", desc:"溢出处理简写", values:"visible | hidden | scroll | auto | clip", initial:"visible", inherited:"否", common:true},
    {name:"overflow-x", desc:"水平溢出", values:"visible | hidden | scroll | auto | clip", initial:"visible", inherited:"否", common:false},
    {name:"overflow-y", desc:"垂直溢出", values:"visible | hidden | scroll | auto | clip", initial:"visible", inherited:"否", common:false},
    {name:"white-space", desc:"空白处理", values:"normal | nowrap | pre | pre-wrap | pre-line | break-spaces", initial:"normal", inherited:"是", common:true},
    {name:"word-break", desc:"单词换行规则", values:"normal | break-all | keep-all | break-word", initial:"normal", inherited:"是", common:false},
    {name:"overflow-wrap", desc:"长词换行", values:"normal | break-word | anywhere", initial:"normal", inherited:"是", common:false},
    {name:"object-fit", desc:"对象适配方式", values:"fill | contain | cover | none | scale-down", initial:"fill", inherited:"否", common:true},
    {name:"object-position", desc:"对象定位", values:"<position>", initial:"50% 50%", inherited:"否", common:false},
    {name:"resize", desc:"是否可调整大小", values:"none | both | horizontal | vertical", initial:"none", inherited:"否", common:false},
    {name:"writing-mode", desc:"书写模式", values:"horizontal-tb | vertical-rl | vertical-lr", initial:"horizontal-tb", inherited:"是", common:false},
    {name:"direction", desc:"文本方向", values:"ltr | rtl", initial:"ltr", inherited:"是", common:false}
  ]},
  {category:"盒模型", props:[
    {name:"width", desc:"宽度", values:"auto | <length> | <percentage> | max-content | min-content | fit-content", initial:"auto", inherited:"否", common:true},
    {name:"height", desc:"高度", values:"auto | <length> | <percentage> | max-content | min-content | fit-content", initial:"auto", inherited:"否", common:true},
    {name:"min-width", desc:"最小宽度", values:"auto | <length> | <percentage>", initial:"auto", inherited:"否", common:true},
    {name:"min-height", desc:"最小高度", values:"<length> | <percentage>", initial:"0", inherited:"否", common:true},
    {name:"max-width", desc:"最大宽度", values:"none | <length> | <percentage>", initial:"none", inherited:"否", common:true},
    {name:"max-height", desc:"最大高度", values:"none | <length> | <percentage>", initial:"none", inherited:"否", common:true},
    {name:"margin", desc:"外边距简写", values:"<length> | <percentage> | auto", initial:"0", inherited:"否", common:true},
    {name:"margin-top", desc:"上外边距", values:"<length> | <percentage> | auto", initial:"0", inherited:"否", common:true},
    {name:"margin-right", desc:"右外边距", values:"<length> | <percentage> | auto", initial:"0", inherited:"否", common:true},
    {name:"margin-bottom", desc:"下外边距", values:"<length> | <percentage> | auto", initial:"0", inherited:"否", common:true},
    {name:"margin-left", desc:"左外边距", values:"<length> | <percentage> | auto", initial:"0", inherited:"否", common:true},
    {name:"padding", desc:"内边距简写", values:"<length> | <percentage>", initial:"0", inherited:"否", common:true},
    {name:"padding-top", desc:"上内边距", values:"<length> | <percentage>", initial:"0", inherited:"否", common:true},
    {name:"padding-right", desc:"右内边距", values:"<length> | <percentage>", initial:"0", inherited:"否", common:true},
    {name:"padding-bottom", desc:"下内边距", values:"<length> | <percentage>", initial:"0", inherited:"否", common:true},
    {name:"padding-left", desc:"左内边距", values:"<length> | <percentage>", initial:"0", inherited:"否", common:true},
    {name:"border", desc:"边框简写", values:"<width> <style> <color>", initial:"medium none currentcolor", inherited:"否", common:true},
    {name:"border-width", desc:"边框宽度", values:"<length> | thin | medium | thick", initial:"medium", inherited:"否", common:true},
    {name:"border-style", desc:"边框样式", values:"none | hidden | dotted | dashed | solid | double | groove | ridge | inset | outset", initial:"none", inherited:"否", common:true},
    {name:"border-color", desc:"边框颜色", values:"<color> | transparent", initial:"currentcolor", inherited:"否", common:true},
    {name:"border-top", desc:"上边框简写", values:"<width> <style> <color>", initial:"medium none currentcolor", inherited:"否", common:true},
    {name:"border-right", desc:"右边框简写", values:"<width> <style> <color>", initial:"medium none currentcolor", inherited:"否", common:true},
    {name:"border-bottom", desc:"下边框简写", values:"<width> <style> <color>", initial:"medium none currentcolor", inherited:"否", common:true},
    {name:"border-left", desc:"左边框简写", values:"<width> <style> <color>", initial:"medium none currentcolor", inherited:"否", common:true},
    {name:"border-radius", desc:"圆角", values:"<length> | <percentage>", initial:"0", inherited:"否", common:true},
    {name:"border-top-left-radius", desc:"左上角圆角", values:"<length> | <percentage>", initial:"0", inherited:"否", common:false},
    {name:"border-top-right-radius", desc:"右上角圆角", values:"<length> | <percentage>", initial:"0", inherited:"否", common:false},
    {name:"border-bottom-right-radius", desc:"右下角圆角", values:"<length> | <percentage>", initial:"0", inherited:"否", common:false},
    {name:"border-bottom-left-radius", desc:"左下角圆角", values:"<length> | <percentage>", initial:"0", inherited:"否", common:false},
    {name:"border-image", desc:"边框图片简写", values:"none | <source> <slice> <width> <outset> <repeat>", initial:"none", inherited:"否", common:false},
    {name:"border-image-source", desc:"边框图片源", values:"none | <image>", initial:"none", inherited:"否", common:false},
    {name:"border-image-slice", desc:"边框图片切片", values:"<number> | <percentage> | fill", initial:"100%", inherited:"否", common:false},
    {name:"border-image-width", desc:"边框图片宽度", values:"<length> | <percentage> | auto | <number>", initial:"1", inherited:"否", common:false},
    {name:"border-image-outset", desc:"边框图片外延", values:"<length> | <number>", initial:"0", inherited:"否", common:false},
    {name:"border-image-repeat", desc:"边框图片重复", values:"stretch | repeat | round | space", initial:"stretch", inherited:"否", common:false},
    {name:"border-collapse", desc:"表格边框合并", values:"collapse | separate", initial:"separate", inherited:"是", common:true},
    {name:"border-spacing", desc:"表格边框间距", values:"<length> <length>", initial:"0", inherited:"是", common:false},
    {name:"box-sizing", desc:"盒模型类型", values:"content-box | border-box", initial:"content-box", inherited:"否", common:true},
    {name:"box-shadow", desc:"盒子阴影", values:"none | <offset-x> <offset-y> <blur> <spread> <color> | inset", initial:"none", inherited:"否", common:true},
    {name:"outline", desc:"轮廓简写", values:"<width> <style> <color>", initial:"none", inherited:"否", common:true},
    {name:"outline-width", desc:"轮廓宽度", values:"<length> | thin | medium | thick", initial:"medium", inherited:"否", common:false},
    {name:"outline-style", desc:"轮廓样式", values:"none | dotted | dashed | solid | double | groove | ridge | inset | outset", initial:"none", inherited:"否", common:false},
    {name:"outline-color", desc:"轮廓颜色", values:"<color> | invert", initial:"invert", inherited:"否", common:false},
    {name:"outline-offset", desc:"轮廓偏移", values:"<length>", initial:"0", inherited:"否", common:false}
  ]},
  {category:"文本与字体", props:[
    {name:"color", desc:"文本颜色", values:"<color>", initial:"currentcolor", inherited:"是", common:true},
    {name:"font-family", desc:"字体族", values:"<family-name> | <generic-family>", initial:"取决于浏览器", inherited:"是", common:true},
    {name:"font-size", desc:"字体大小", values:"<length> | <percentage> | xx-small | x-small | small | medium | large | x-large | xx-large | larger | smaller", initial:"medium", inherited:"是", common:true},
    {name:"font-weight", desc:"字体粗细", values:"normal | bold | bolder | lighter | 100-900", initial:"normal", inherited:"是", common:true},
    {name:"font-style", desc:"字体样式", values:"normal | italic | oblique", initial:"normal", inherited:"是", common:true},
    {name:"font-variant", desc:"字体变体", values:"normal | small-caps | all-small-caps", initial:"normal", inherited:"是", common:false},
    {name:"font-stretch", desc:"字体拉伸", values:"normal | condensed | expanded", initial:"normal", inherited:"是", common:false},
    {name:"font-display", desc:"字体显示策略", values:"auto | block | swap | fallback | optional", initial:"auto", inherited:"否", common:false},
    {name:"font", desc:"字体简写", values:"<style> <variant> <weight> <size>/<line-height> <family>", initial:"取决于浏览器", inherited:"是", common:true},
    {name:"line-height", desc:"行高", values:"normal | <length> | <percentage> | <number>", initial:"normal", inherited:"是", common:true},
    {name:"text-align", desc:"文本对齐", values:"start | end | left | right | center | justify", initial:"start", inherited:"是", common:true},
    {name:"text-align-last", desc:"最后一行对齐", values:"auto | start | end | left | right | center | justify", initial:"auto", inherited:"是", common:false},
    {name:"text-decoration", desc:"文本装饰简写", values:"none | underline || overline || line-through", initial:"none", inherited:"否", common:true},
    {name:"text-decoration-line", desc:"装饰线类型", values:"none | underline | overline | line-through", initial:"none", inherited:"否", common:false},
    {name:"text-decoration-color", desc:"装饰线颜色", values:"<color>", initial:"currentcolor", inherited:"否", common:false},
    {name:"text-decoration-style", desc:"装饰线样式", values:"solid | double | dotted | dashed | wavy", initial:"solid", inherited:"否", common:false},
    {name:"text-decoration-thickness", desc:"装饰线粗细", values:"<length> | auto | from-font", initial:"auto", inherited:"否", common:false},
    {name:"text-underline-offset", desc:"下划线偏移", values:"auto | <length> | <percentage>", initial:"auto", inherited:"否", common:false},
    {name:"text-indent", desc:"首行缩进", values:"<length> | <percentage>", initial:"0", inherited:"是", common:true},
    {name:"text-transform", desc:"文本大小写", values:"none | capitalize | uppercase | lowercase | full-width", initial:"none", inherited:"是", common:true},
    {name:"text-shadow", desc:"文本阴影", values:"none | <offset-x> <offset-y> <blur> <color>", initial:"none", inherited:"否", common:true},
    {name:"letter-spacing", desc:"字符间距", values:"normal | <length>", initial:"normal", inherited:"是", common:true},
    {name:"word-spacing", desc:"单词间距", values:"normal | <length> | <percentage>", initial:"normal", inherited:"是", common:false},
    {name:"hyphens", desc:"连字符", values:"none | manual | auto", initial:"manual", inherited:"是", common:false},
    {name:"text-rendering", desc:"文本渲染优化", values:"auto | optimizeSpeed | optimizeLegibility | geometricPrecision", initial:"auto", inherited:"是", common:false},
    {name:"text-size-adjust", desc:"文本大小调整", values:"auto | none | <percentage>", initial:"auto", inherited:"是", common:true},
    {name:"hanging-punctuation", desc:"悬挂标点", values:"none | first | last | allow-end | force-end", initial:"none", inherited:"是", common:false},
    {name:"font-synthesis", desc:"字体合成", values:"none | weight | style | small-caps", initial:"weight style", inherited:"是", common:false},
    {name:"text-emphasis", desc:"强调标记简写", values:"none | [ <style> || <color> ]", initial:"none", inherited:"是", common:false},
    {name:"text-emphasis-style", desc:"强调标记样式", values:"none | filled | open | dot | circle | double-circle | triangle | sesame", initial:"none", inherited:"是", common:false},
    {name:"text-emphasis-color", desc:"强调标记颜色", values:"<color>", initial:"currentcolor", inherited:"是", common:false},
    {name:"text-emphasis-position", desc:"强调标记位置", values:"over | under | right | left", initial:"over right", inherited:"是", common:false}
  ]},
  {category:"背景", props:[
    {name:"background", desc:"背景简写", values:"<bg-layer># | <final-bg-layer>", initial:"取决于子属性", inherited:"否", common:true},
    {name:"background-color", desc:"背景颜色", values:"<color> | transparent", initial:"transparent", inherited:"否", common:true},
    {name:"background-image", desc:"背景图片", values:"none | <image>#", initial:"none", inherited:"否", common:true},
    {name:"background-repeat", desc:"背景重复", values:"repeat | repeat-x | repeat-y | no-repeat | space | round", initial:"repeat", inherited:"否", common:true},
    {name:"background-position", desc:"背景位置", values:"<position>", initial:"0% 0%", inherited:"否", common:true},
    {name:"background-size", desc:"背景尺寸", values:"auto | <length> | <percentage> | cover | contain", initial:"auto", inherited:"否", common:true},
    {name:"background-attachment", desc:"背景滚动", values:"scroll | fixed | local", initial:"scroll", inherited:"否", common:true},
    {name:"background-origin", desc:"背景起点", values:"padding-box | border-box | content-box", initial:"padding-box", inherited:"否", common:false},
    {name:"background-clip", desc:"背景裁剪", values:"border-box | padding-box | content-box | text", initial:"border-box", inherited:"否", common:true},
    {name:"background-blend-mode", desc:"背景混合模式", values:"normal | multiply | screen | overlay | darken | lighten | color-dodge | color-burn | hard-light | soft-light | difference | exclusion | hue | saturation | color | luminosity", initial:"normal", inherited:"否", common:false}
  ]},
  {category:"视觉效果", props:[
    {name:"opacity", desc:"透明度", values:"<number> (0-1)", initial:"1", inherited:"否", common:true},
    {name:"filter", desc:"滤镜效果", values:"none | blur() | brightness() | contrast() | drop-shadow() | grayscale() | hue-rotate() | invert() | opacity() | saturate() | sepia()", initial:"none", inherited:"否", common:true},
    {name:"backdrop-filter", desc:"背景滤镜", values:"none | <filter-function>", initial:"none", inherited:"否", common:true},
    {name:"mix-blend-mode", desc:"混合模式", values:"normal | multiply | screen | overlay | darken | lighten | color-dodge | color-burn | hard-light | soft-light | difference | exclusion | hue | saturation | color | luminosity", initial:"normal", inherited:"否", common:false},
    {name:"isolation", desc:"隔离混合", values:"auto | isolate", initial:"auto", inherited:"否", common:false},
    {name:"will-change", desc:"性能提示", values:"auto | scroll-position | contents | <custom-ident>", initial:"auto", inherited:"否", common:false},
    {name:"perspective", desc:"透视距离", values:"none | <length>", initial:"none", inherited:"否", common:true},
    {name:"perspective-origin", desc:"透视原点", values:"<position>", initial:"50% 50%", inherited:"否", common:false},
    {name:"backface-visibility", desc:"背面可见性", values:"visible | hidden", initial:"visible", inherited:"否", common:true},
    {name:"clip-path", desc:"裁剪路径", values:"none | <clip-source> | [ <basic-shape> || <geometry-box> ]", initial:"none", inherited:"否", common:true},
    {name:"mask", desc:"遮罩简写", values:"none | <mask-layer>#", initial:"none", inherited:"否", common:false},
    {name:"mask-image", desc:"遮罩图片", values:"none | <image>#", initial:"none", inherited:"否", common:false},
    {name:"mask-mode", desc:"遮罩模式", values:"match-source | alpha | luminance", initial:"match-source", inherited:"否", common:false},
    {name:"mask-repeat", desc:"遮罩重复", values:"repeat | no-repeat | repeat-x | repeat-y | space | round", initial:"repeat", inherited:"否", common:false},
    {name:"mask-position", desc:"遮罩位置", values:"<position>", initial:"center", inherited:"否", common:false},
    {name:"mask-size", desc:"遮罩尺寸", values:"auto | <length> | <percentage> | cover | contain", initial:"auto", inherited:"否", common:false},
    {name:"mask-composite", desc:"遮罩混合", values:"add | subtract | intersect | exclude", initial:"add", inherited:"否", common:false},
    {name:"mask-border", desc:"遮罩边框简写", values:"<mask-border-source> || <mask-border-slice> || <mask-border-width> || <mask-border-outset> || <mask-border-repeat> || <mask-border-mode>", initial:"none", inherited:"否", common:false}
  ]},
  {category:"变换与动画", props:[
    {name:"transform", desc:"变换", values:"none | translate() | scale() | rotate() | skew() | matrix() | perspective()", initial:"none", inherited:"否", common:true},
    {name:"transform-origin", desc:"变换原点", values:"<position>", initial:"50% 50% 0", inherited:"否", common:true},
    {name:"transform-style", desc:"3D变换风格", values:"flat | preserve-3d", initial:"flat", inherited:"否", common:true},
    {name:"transition", desc:"过渡简写", values:"<property> <duration> <timing-function> <delay>", initial:"all 0s ease 0s", inherited:"否", common:true},
    {name:"transition-property", desc:"过渡属性", values:"none | all | <property-name>", initial:"all", inherited:"否", common:false},
    {name:"transition-duration", desc:"过渡时长", values:"<time>", initial:"0s", inherited:"否", common:false},
    {name:"transition-timing-function", desc:"过渡时间函数", values:"linear | ease | ease-in | ease-out | ease-in-out | cubic-bezier() | steps()", initial:"ease", inherited:"否", common:false},
    {name:"transition-delay", desc:"过渡延迟", values:"<time>", initial:"0s", inherited:"否", common:false},
    {name:"animation", desc:"动画简写", values:"<name> <duration> <timing-function> <delay> <iteration-count> <direction> <fill-mode> <play-state>", initial:"none 0s ease 0s 1 normal none running", inherited:"否", common:true},
    {name:"animation-name", desc:"动画名称", values:"none | <keyframe-name>", initial:"none", inherited:"否", common:false},
    {name:"animation-duration", desc:"动画时长", values:"<time>", initial:"0s", inherited:"否", common:false},
    {name:"animation-timing-function", desc:"动画时间函数", values:"linear | ease | ease-in | ease-out | ease-in-out | cubic-bezier() | steps()", initial:"ease", inherited:"否", common:false},
    {name:"animation-delay", desc:"动画延迟", values:"<time>", initial:"0s", inherited:"否", common:false},
    {name:"animation-iteration-count", desc:"动画次数", values:"<number> | infinite", initial:"1", inherited:"否", common:false},
    {name:"animation-direction", desc:"动画方向", values:"normal | reverse | alternate | alternate-reverse", initial:"normal", inherited:"否", common:false},
    {name:"animation-fill-mode", desc:"动画填充模式", values:"none | forwards | backwards | both", initial:"none", inherited:"否", common:false},
    {name:"animation-play-state", desc:"动画播放状态", values:"running | paused", initial:"running", inherited:"否", common:false}
  ]},
  {category:"列表与表格", props:[
    {name:"list-style", desc:"列表样式简写", values:"<type> <position> <image>", initial:"取决于子属性", inherited:"是", common:true},
    {name:"list-style-type", desc:"列表标记类型", values:"disc | circle | square | decimal | lower-alpha | upper-alpha | lower-roman | upper-roman | none", initial:"disc", inherited:"是", common:true},
    {name:"list-style-position", desc:"列表标记位置", values:"inside | outside", initial:"outside", inherited:"是", common:false},
    {name:"list-style-image", desc:"列表标记图片", values:"none | <image>", initial:"none", inherited:"是", common:false},
    {name:"table-layout", desc:"表格布局", values:"auto | fixed", initial:"auto", inherited:"否", common:true},
    {name:"caption-side", desc:"表格标题位置", values:"top | bottom | block-start | block-end", initial:"top", inherited:"是", common:false},
    {name:"empty-cells", desc:"空单元格显示", values:"show | hide", initial:"show", inherited:"是", common:false},
    {name:"marker", desc:"列表标记简写", values:"none | <content> | <marker>", initial:"none", inherited:"是", common:false}
  ]},
  {category:"多列布局", props:[
    {name:"columns", desc:"列数简写", values:"<column-width> || <column-count>", initial:"auto auto", inherited:"否", common:true},
    {name:"column-width", desc:"列宽", values:"auto | <length>", initial:"auto", inherited:"否", common:true},
    {name:"column-count", desc:"列数", values:"auto | <integer>", initial:"auto", inherited:"否", common:true},
    {name:"column-rule", desc:"列分隔线简写", values:"<width> <style> <color>", initial:"none", inherited:"否", common:false},
    {name:"column-span", desc:"跨列", values:"none | all", initial:"none", inherited:"否", common:false},
    {name:"column-fill", desc:"列填充方式", values:"auto | balance | balance-all", initial:"balance", inherited:"否", common:false},
    {name:"break-inside", desc:"内部断行", values:"auto | avoid | avoid-page | avoid-column | avoid-region", initial:"auto", inherited:"否", common:false},
    {name:"break-before", desc:"前置断行", values:"auto | avoid | page | always | left | right | column | region", initial:"auto", inherited:"否", common:false},
    {name:"break-after", desc:"后置断行", values:"auto | avoid | page | always | left | right | column | region", initial:"auto", inherited:"否", common:false},
    {name:"orphans", desc:"孤行控制", values:"<integer>", initial:"2", inherited:"是", common:false},
    {name:"widows", desc:"寡行控制", values:"<integer>", initial:"2", inherited:"是", common:false}
  ]},
  {category:"生成内容", props:[
    {name:"content", desc:"生成内容", values:"normal | none | <content-list>", initial:"normal", inherited:"否", common:true},
    {name:"counter-reset", desc:"计数器重置", values:"<identifier> <integer>? | none", initial:"none", inherited:"否", common:true},
    {name:"counter-increment", desc:"计数器递增", values:"<identifier> <integer>? | none", initial:"none", inherited:"否", common:true},
    {name:"quotes", desc:"引号样式", values:"auto | <string> <string>+ | none", initial:"auto", inherited:"是", common:false}
  ]},
  {category:"用户界面", props:[
    {name:"cursor", desc:"鼠标光标", values:"auto | default | none | pointer | help | wait | text | move | grab | crosshair", initial:"auto", inherited:"是", common:true},
    {name:"caret-color", desc:"光标颜色", values:"auto | <color>", initial:"auto", inherited:"否", common:true},
    {name:"pointer-events", desc:"指针事件", values:"auto | none | visible | ...", initial:"auto", inherited:"否", common:true},
    {name:"user-select", desc:"用户选择", values:"auto | none | text | contain | all", initial:"auto", inherited:"否", common:true},
    {name:"appearance", desc:"外观", values:"none | auto | button | textfield | ...", initial:"auto", inherited:"否", common:true},
    {name:"nav", desc:"导航焦点顺序", values:"auto | <id>", initial:"auto", inherited:"否", common:false},
    {name:"scrollbar-width", desc:"滚动条宽度", values:"auto | thin | none", initial:"auto", inherited:"否", common:false},
    {name:"scrollbar-color", desc:"滚动条颜色", values:"auto | <color> <color>", initial:"auto", inherited:"否", common:false}
  ]},
  {category:"滚动行为", props:[
    {name:"scroll-behavior", desc:"滚动行为", values:"auto | smooth", initial:"auto", inherited:"否", common:true},
    {name:"scroll-snap-type", desc:"滚动吸附类型", values:"none | x | y | both | mandatory | proximity", initial:"none", inherited:"否", common:false},
    {name:"scroll-snap-align", desc:"滚动吸附对齐", values:"none | start | end | center", initial:"none", inherited:"否", common:false},
    {name:"scroll-snap-stop", desc:"滚动吸附停止", values:"normal | always", initial:"normal", inherited:"否", common:false},
    {name:"scroll-margin", desc:"滚动外边距简写", values:"<length>", initial:"0", inherited:"否", common:false},
    {name:"scroll-margin-top", desc:"上滚动外边距", values:"<length>", initial:"0", inherited:"否", common:false},
    {name:"scroll-margin-right", desc:"右滚动外边距", values:"<length>", initial:"0", inherited:"否", common:false},
    {name:"scroll-margin-bottom", desc:"下滚动外边距", values:"<length>", initial:"0", inherited:"否", common:false},
    {name:"scroll-margin-left", desc:"左滚动外边距", values:"<length>", initial:"0", inherited:"否", common:false},
    {name:"scroll-padding", desc:"滚动内边距简写", values:"<length> | auto", initial:"auto", inherited:"否", common:false},
    {name:"scroll-padding-top", desc:"上滚动内边距", values:"<length> | auto", initial:"auto", inherited:"否", common:false},
    {name:"scroll-padding-right", desc:"右滚动内边距", values:"<length> | auto", initial:"auto", inherited:"否", common:false},
    {name:"scroll-padding-bottom", desc:"下滚动内边距", values:"<length> | auto", initial:"auto", inherited:"否", common:false},
    {name:"scroll-padding-left", desc:"左滚动内边距", values:"<length> | auto", initial:"auto", inherited:"否", common:false},
    {name:"scrollbar-gutter", desc:"滚动条占位", values:"auto | stable | both-edges", initial:"auto", inherited:"否", common:false}
  ]},
  {category:"其他属性", props:[
    {name:"all", desc:"所有属性重置", values:"initial | inherit | unset | revert", initial:"取决于浏览器", inherited:"否", common:false},
    {name:"content-visibility", desc:"内容可见性", values:"visible | hidden | auto", initial:"visible", inherited:"否", common:false},
    {name:"contain", desc:"包含关系", values:"none | layout | paint | size | style | strict | content", initial:"none", inherited:"否", common:false},
    {name:"container-type", desc:"容器查询类型", values:"normal | inline-size | size", initial:"normal", inherited:"否", common:false},
    {name:"container-name", desc:"容器名称", values:"<custom-ident>", initial:"", inherited:"否", common:false},
    {name:"accent-color", desc:"强调色", values:"auto | <color>", initial:"auto", inherited:"否", common:true},
    {name:"color-scheme", desc:"配色方案", values:"normal | light | dark | light dark", initial:"normal", inherited:"是", common:true},
    {name:"forced-color-adjust", desc:"强制颜色调整", values:"auto | none", initial:"auto", inherited:"是", common:false},
    {name:"image-rendering", desc:"图片渲染", values:"auto | crisp-edges | pixelated | smooth", initial:"auto", inherited:"否", common:false},
    {name:"shape-outside", desc:"形状外面", values:"none | <shape> | <image>", initial:"none", inherited:"否", common:false},
    {name:"shape-margin", desc:"形状外边距", values:"<length> | <percentage>", initial:"0", inherited:"否", common:false},
    {name:"shape-image-threshold", desc:"形状图像阈值", values:"<number> (0-1)", initial:"0", inherited:"否", common:false},
    {name:"offset", desc:"偏移路径简写", values:"<path> <distance> <rotation> <anchor>", initial:"取决于子属性", inherited:"否", common:false},
    {name:"offset-path", desc:"偏移路径", values:"none | <path> | <url>", initial:"none", inherited:"否", common:false},
    {name:"offset-distance", desc:"偏移距离", values:"<length> | <percentage>", initial:"0", inherited:"否", common:false},
    {name:"offset-rotate", desc:"偏移旋转", values:"auto | <angle> | [auto && <angle>]", initial:"auto", inherited:"否", common:false},
    {name:"unicode-bidi", desc:"双向文本", values:"normal | embed | isolate | bidi-override | isolate-override | plaintext", initial:"normal", inherited:"否", common:false},
    {name:"text-combine-upright", desc:"竖排组合", values:"none | all | digits <number>", initial:"none", inherited:"是", common:false},
    {name:"text-orientation", desc:"文本方向", values:"mixed | upright | sideways", initial:"mixed", inherited:"是", common:false}
  ]}
];
